# Generated by Django 5.1 on 2025-03-31 20:39

import django.db.models.deletion
import pozmvm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=pozmvm.models.upload_to)),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pozmvm.uploadentry')),
            ],
        ),
    ]
