# Generated by Django 5.1 on 2025-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozmvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadentry',
            name='descripcion',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='tipo_archivo',
            field=models.CharField(max_length=100),
        ),
    ]
