# Generated by Django 5.1 on 2025-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto (máximo 100 caracteres)', max_length=100, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(help_text='Descripción del proyecto (máximo 500 caracteres)', max_length=500, verbose_name='Descripción')),
                ('municipalities', models.JSONField(help_text='Lista de municipios seleccionados', verbose_name='Municipios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Formulario del Chat',
                'verbose_name_plural': 'Formularios del Chat',
            },
        ),
    ]
